version: "3"
services:
  app:
    container_name: app
    build: ./app/
    command: python3 -u app/app.py --host db
    volumes:
    - .:/app
    ports:
      - "5000:5000"
    links:
      - mongo
    networks:
      - backend
      - frontend

  mongo:
    image: mongo:6.0.2
    networks:
      - backend

  mongo_seed:
    image: mongo:6.0.2
    links:
      - mongo
    networks:
      - backend
    volumes:
      - ./mongo-seed:/mongo-seed/
    command:
      /mongo-seed/import.sh

networks:
  backend:
    driver: "bridge"
  frontend:
    driver: "bridge"